---
branches:
  only:
  - source
language: ruby
rvm:
- 1.9.3
before_script:
- git config --global user.name "xhhjin"
- git config --global user.email "xhhjin@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- bundle exec rake setup_github_pages[$REPO_URL]
script:
- set LANG=zh_CN.UTF-8
- bundle exec rake generate
after_script:
- bundle exec rake deploy
env:
  global:
  - GH_REPO="xhhjin/xhhjin.github.com"
  - secure: "AE/ullWCQ7kBYVWxJU1Bj/7HkQUzb6jOKR8EjmWDSspL1zs0jZmS20d2bXLkhS/Ryz5j+sD4N4/CE7SY1GVtW+wze9nXMGW+ZJaY6rrP7uEkAO1vcErigyl8hbpf6CiRpBbYd/u/WPPmtr2+5Y2LZ+t8ySM7Jdg8+q9YqEwiISM="
