---
branches:
  only:
  - source
language: ruby
rvm:
- 1.9.3
before_script:
- git config --global user.name "xhhjin"
- git config --global user.email "xhhjin@gmail.com"
- export REPO_URL="https://$GH_TOKEN1@github.com/$GH_REPO.git"
- bundle exec rake setup_github_pages[$REPO_URL]
script:
- bundle exec rake generate
after_script:
- bundle exec rake deploy
env:
  global:
  - GH_REPO="xhhjin/xhhjin.github.com"
  - GH_TOKEN1=dcde6fe8f5daf3de1321f01836ba0009f474f500
  - secure: "thEfITzWkMx8nOACts8pvJK9Ozhjxixt/KFwQyyQ4AheF71HR/cA6GQHjFXGGXNx9j9iMOTtIRXdP0NtsEenjbqokqnll/uRif4d+xNMs8Qj+Rhc83LTbDf6ePfhgcEVX+UZRjhesIRzWaE0159hL8vKAuMW0llIzoqbFZv9zt0="
