---
branches:
  only:
  - source
language: ruby
rvm:
- 1.9.3
before_script:
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- bundle exec rake setup_github_pages[$REPO_URL]
script:
- bundle exec rake generate
after_script:
- bundle exec rake deploy
env:
  global:
  - GH_REPO="git@github.com:xhhjin/xhhjin.github.io"
  - secure:"Bme2RMigvmRcGMtDSGTV/kUNnuhY+yFE/KbEUFbJFv/EPulWPv/ETuZ4/TOpD3Ti9oHgpX36nRfcVhuI0AjeY+vYuQNFhv1Ju4CvM0o4BSiUYnVkp8yKf6/qU9bn1tEOFvN+MzzIBTxG9bm1Iv4JxoMDwXlmAg8W9mWI59ANQsk="